- generic:
  - generic:
    - generic:
      - complementary:
        - generic:
          - img
          - generic:
            - paragraph: Tur Planlayıcı
            - paragraph: Şəxsi tur planlayıcınız
        - navigation:
          - link:
            - /url: /
            - img
            - text: Ana səhifə
          - link:
            - /url: /tours
            - img
            - text: Turlar
          - link:
            - /url: /calendar
            - img
            - text: Təqvim
          - link:
            - /url: /search
            - img
            - text: Axtarış
          - link:
            - /url: /ai
            - img
            - text: AI Köməkçi
          - link:
            - /url: /settings
            - img
            - text: Tənzimləmələr
        - generic:
          - button:
            - generic:
              - generic: A
            - generic:
              - paragraph: admin
              - paragraph: "Rol: Administrator"
      - generic:
        - main:
          - generic:
            - generic:
              - button:
                - img
              - heading [level=1]: test
          - generic:
            - generic:
              - generic:
                - generic:
                  - generic:
                    - generic:
                      - img
                      - text: Tur təfərrüatı
                    - generic:
                      - generic: Tamamlanıb
                  - generic:
                    - generic:
                      - heading [level=1]: test
                      - generic:
                        - generic:
                          - generic:
                            - img
                            - text: Başlama tarixi
                          - paragraph: 17 — 17 İyul
                        - generic:
                          - generic:
                            - img
                            - text: gün
                          - paragraph: 1 gün · 1 tədbir
                      - paragraph: test
                    - generic:
                      - button:
                        - img
                        - text: Redaktə et
                      - button:
                        - img
                        - text: Sil
                  - img
              - generic:
                - generic:
                  - heading [level=2]:
                    - img
                    - text: Qonaqlar
                    - generic: (0)
                  - button:
                    - img
                    - generic: Qonaq əlavə et
                - generic: Bu tura turist əlavə edin
              - generic:
                - generic:
                  - generic:
                    - generic: "1"
                  - generic:
                    - generic:
                      - heading [level=3]: 1-ci gün
                      - paragraph: 17 İyul
                    - button:
                      - img
                      - generic: Tədbir əlavə et
                  - generic:
                    - generic:
                      - generic:
                        - generic:
                          - generic:
                            - img
                          - generic:
                            - generic:
                              - generic:
                                - paragraph: test
                                - paragraph: Transfer
                              - button:
                                - img
                            - generic:
                              - generic:
                                - img
                                - generic: 19:50
                              - generic:
                                - img
                                - generic: test
                              - generic:
                                - img
                                - generic: test
                              - generic:
                                - img
                                - text: test
                            - generic:
                              - generic: Planlaşdırılıb
                              - generic: Ödənilməyib
                              - generic: 12 ₼
  - region "Notifications alt+T"
  - button "Open Next.js Dev Tools" [ref=e204] [cursor=pointer]:
    - img [ref=e205]
  - alert
  - dialog "Qonaq əlavə et" [ref=e209]:
    - heading "Qonaq əlavə et" [level=2] [ref=e211]
    - generic [ref=e212]:
      - generic [ref=e213]:
        - generic [ref=e214]: Ad, soyad
        - textbox "Ad, soyad" [active] [ref=e215]
      - generic [ref=e216]:
        - generic [ref=e217]:
          - text: Telefon
          - generic [ref=e218]: (istəyə bağlı)
        - textbox "+994 50 123 45 67" [ref=e219]
      - generic [ref=e220]:
        - generic [ref=e221]:
          - generic [ref=e222]:
            - text: Pasport nömrəsi
            - generic [ref=e223]: (istəyə bağlı)
          - textbox "AA1234567" [ref=e224]
        - generic [ref=e225]:
          - generic [ref=e226]:
            - text: Vətəndaşlıq
            - generic [ref=e227]: (istəyə bağlı)
          - textbox "Azərbaycan" [ref=e228]
      - generic [ref=e229]:
        - generic [ref=e230]:
          - text: Qeydlər
          - generic [ref=e231]: (istəyə bağlı)
        - textbox "Qeydlər" [ref=e232]
    - generic [ref=e233]:
      - button "Ləğv et" [ref=e234] [cursor=pointer]
      - button "Yadda saxla" [ref=e235] [cursor=pointer]
    - button "Bağla" [ref=e236] [cursor=pointer]:
      - img [ref=e237]
      - generic [ref=e240]: Bağla