- generic:
  - generic:
    - generic:
      - complementary:
        - generic:
          - img
          - generic:
            - paragraph: Tur Planlayıcı
            - paragraph: Şəxsi tur planlayıcınız
        - navigation:
          - link:
            - /url: /
            - img
            - text: Ana səhifə
          - link:
            - /url: /tours
            - img
            - text: Turlar
          - link:
            - /url: /calendar
            - img
            - text: Təqvim
          - link:
            - /url: /search
            - img
            - text: Axtarış
          - link:
            - /url: /ai
            - img
            - text: AI Köməkçi
          - link:
            - /url: /settings
            - img
            - text: Tənzimləmələr
        - generic:
          - button:
            - generic:
              - generic: A
            - generic:
              - paragraph: admin
              - paragraph: "Rol: Administrator"
      - generic:
        - main:
          - generic:
            - generic:
              - button:
                - img
              - heading [level=1]: test
          - generic:
            - generic:
              - generic:
                - generic:
                  - generic:
                    - generic:
                      - img
                      - text: Tur təfərrüatı
                    - generic:
                      - generic: Tamamlanıb
                  - generic:
                    - generic:
                      - heading [level=1]: test
                      - generic:
                        - generic:
                          - generic:
                            - img
                            - text: Başlama tarixi
                          - paragraph: 17 — 17 İyul
                        - generic:
                          - generic:
                            - img
                            - text: gün
                          - paragraph: 1 gün · 1 tədbir
                      - paragraph: test
                    - generic:
                      - button:
                        - img
                        - text: Redaktə et
                      - button:
                        - img
                        - text: Sil
                  - img
              - generic:
                - generic:
                  - generic:
                    - generic: "1"
                  - generic:
                    - generic:
                      - heading [level=3]: 1-ci gün
                      - paragraph: 17 İyul
                    - button:
                      - img
                      - generic: Tədbir əlavə et
                  - generic:
                    - generic:
                      - generic:
                        - generic:
                          - generic:
                            - img
                          - generic:
                            - generic:
                              - generic:
                                - paragraph: test
                                - paragraph: Transfer
                              - button:
                                - img
                            - generic:
                              - generic:
                                - img
                                - generic: 19:50
                              - generic:
                                - img
                                - generic: test
                              - generic:
                                - img
                                - generic: test
                              - generic:
                                - img
                                - text: test
                            - generic:
                              - generic: Planlaşdırılıb
                              - generic: Ödənilməyib
                              - generic: 12 ₼
  - region "Notifications alt+T"
  - button "Open Next.js Dev Tools" [ref=f3e16] [cursor=pointer]:
    - img [ref=f3e17]
  - alert
  - dialog:
    - generic:
      - heading [level=2]: Yeni tədbir
      - paragraph: 17 İyul
    - generic:
      - generic:
        - generic: Başlıq
        - textbox:
          - /placeholder: Başlıq
      - generic:
        - generic:
          - generic: Növ
          - combobox [expanded]:
            - generic:
              - generic:
                - img
                - text: Digər
            - img
          - combobox
        - generic:
          - generic: Status
          - combobox:
            - generic: Planlaşdırılıb
            - img
          - combobox
      - generic:
        - generic:
          - generic: Tarix
          - button:
            - img
            - generic: 17 İyul 2026
        - generic:
          - generic:
            - text: Saat
            - generic: (istəyə bağlı)
          - textbox
      - button:
        - text: Daha çox detal
        - img
    - generic:
      - button: Ləğv et
      - button: Yadda saxla
    - button:
      - img
      - generic: Bağla
  - listbox [ref=f3e64]:
    - option "Transfer" [ref=f3e65] [cursor=pointer]:
      - generic [ref=f3e68]:
        - img [ref=f3e69]
        - text: Transfer
    - option "Otel" [ref=f3e73] [cursor=pointer]:
      - generic [ref=f3e76]:
        - img [ref=f3e77]
        - text: Otel
    - option "Restoran" [ref=f3e80] [cursor=pointer]:
      - generic [ref=f3e83]:
        - img [ref=f3e84]
        - text: Restoran
    - option "Digər" [active] [selected] [ref=f3e89] [cursor=pointer]:
      - img [ref=f3e92]
      - generic [ref=f3e95]:
        - img [ref=f3e96]
        - text: Digər